### ISSUE TITLE
文件Queue单机多进程情况下同时写入同一个文件不能用

### ISSUE THREAD

**Issue by daoxian** [peter-wangxu/persist-queue#103]
老哥， 这种情况下无法持续消费，会卡在那里不动

**Comment by peter-wangxu** [comment]
这是一个已知的限制了, 多进程确实会有问题，可能需要引入文件锁，速度上会下降比较多。

考虑下是否可以使用Sqlite queue

**Comment by peter-wangxu** [comment]
@daoxian 麻烦提供下代码示例，我准备等段时间支持下多进程的读写访问。

**Comment by daoxian** [comment]
shell里起多个写入实例就好了

**Comment by peter-wangxu** [comment]
先关闭，如果有问题再开
