### ISSUE TITLE
SQLite based Queues performance issue

### ISSUE THREAD

**Issue by daniyalDE** [peter-wangxu/persist-queue#104]
I have a Debian VM, i am working with File based queues as well as SQLiteAckQueue. The file based queues work perfectly however all the sqlite based queues are super slow. Initializing a queue itself may take upto 30 seconds or more and then each read/write is just as long. I tried the benchmark & tests and everything there seemed fine. 

Also i have tried executing read/write queries through sqlite on the same database and there seem to be no issues there. Also i would like to point out i have tried this with multiple versions of python on my machine and still no luck.

On Mac it seems to work , don't know what could be the issue here.

**Comment by peter-wangxu** [comment]
Can you please share some pseudo-code of your slow queue and the filesystem info?
the benchmark tests are running on tmp which different than where you locate the sqlite queue.

**Comment by daniyalDE** [comment]
I can confirm that the issue was related to the disk partition i was using. The data was essentially going through different network and encryption layers before being written to that disk, i created a new partition and tested the queues on it and everything seems to be working perfectly.
