### ISSUE TITLE
What happens in the case that disk space ran out?

### ISSUE THREAD

**Issue by chr15stevens** [peter-wangxu/persist-queue#107]
Not sure if this is the right place to ask but I don't think there was any documentation on it.

What happens if the entire disk is used?
What happens in the case maxsize is set and reached?
Has there been much use around large queues?

**Comment by peter-wangxu** [comment]
> Not sure if this is the right place to ask but I don't think there was any documentation on it.
> 
> What happens if the entire disk is used?
you should notice an error while putting
> What happens in the case maxsize is set and reached?
you will go exception `Full`
> Has there been much use around large queues?
I haven't test that, but according a user, queue file can be as large as several MiB

**Comment by chr15stevens** [comment]
Thanks for your reply Peter. So if I was looking for a persistent queue that would work up to potentially many GB would you advise your solution?

**Comment by peter-wangxu** [comment]
It's not recommended to store huge data in file queue, instead sqlite queue should be fine for your case.
I did a perf test on my mac, here is result:
```python
In [1]: count=5000000 # 5 million entries

In [2]: from persistqueue import SQLiteQueue

In [3]: q = SQLiteQueue(path="data", name="hello")

In [4]: timeit

In [5]: timeit?

In [6]: def write_perf(c):
   ...:     for x in range(1, c):
   ...:         q.put({"key": "xxxxxx" * (c % 10)})
   ...:

In [7]: def read_perf(c):
   ...:     for x in range(1, c):
   ...:         q.get()
   ...:

In [8]: %timeit -n 1 -r 2 write_perf(count)
10min 8s ± 5.04 s per loop (mean ± std. dev. of 2 runs, 1 loop each)

```
and the queue size is around 500MiB:

```bash
(persist-queue) ➜  data git:(master) ✗ ls -lh
total 860360
-rw-r--r--  1 peter staff   411M Sep  7 01:02 data.db
-rw-r--r--  1 peter  staff    32K Sep  7 00:23 data.db-shm
-rw-r--r--  1 peter  staff   4.0M Sep  7 01:02 data.db-wal

```

Hope above stats could help you.

**Comment by chr15stevens** [comment]
Thanks Peter, I will give this a go!
Do you think there maybe should be a way to configure what happens on max size reach (or disk full) removing first or last entry or something?

**Comment by luann-trend** [comment]
I have tried it out both file queue and sql queue, it seems like the space never reclaim even though the entries are removed from the queue.

**Comment by peter-wangxu** [comment]
For file queue, the `task_done` should fulfill that

while for sql queue, you may need to perform manual `VACCUM`( https://sqlite.org/lang_vacuum.html)
