### ISSUE TITLE
Attribute 'queue' (used to get a copy of the data) missing from Queue in persistqueue

### ISSUE THREAD

**Issue by lautaromss** [peter-wangxu/persist-queue#124]
In the standard Queue from python we can access the attribute queue to get a copy of the data, like so:

```
>>> from queue import Queue
>>> q = Queue()
>>> q.put('a')
>>> q.put('b')
>>> print(q)
<queue.Queue object at 0x01CEA310>
>>> print(q.queue)
deque(['a', 'b'])
>>> for elem in q.queue:
...   print(elem)
a
b
>>> q.get()
'a'
>>> q.get()
'b'
```

Notice that q.queue is an iterable object that contains each element of the queue, and since it's a copy of the data, accessing it doesn't modify the actual queue (when you use get(), you still get the first element). In contrast, the actual queue 'q' is not iterable and if you try to print it, it will not show you the data inside it.

This .queue attribute is very useful for logging purposes and also in automated tests to do assertions with the data inside the queue.

I want to replace my current queue with a persistent queue, but I ran into the following problem when trying to access that .queue attribute

```
>>> q.queue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Queue' object has no attribute 'queue'
```

**Do you have any suggestions on how I could access the "persistent queue" data without actually modifying the queue for logging and automated testing purposes?**

Thanks!

**Comment by peter-wangxu** [comment]
you may give a try with `PDict` which supports iteration over the it. 
I will also consider it a feature for file queue.

**Comment by deepnarainsingh** [comment]
Hi @peter-wangxu  is this feature available for the file queue ?
