### ISSUE TITLE
Cannot make multiple objects

### ISSUE THREAD

**Issue by varungujarathi9** [peter-wangxu/persist-queue#125]
Currently, it is unable to work with multiple objects of class Queue since it reads from the latest file created by the` _qfile` method. This should not be the case, it should read from the explicit file created for that object. I can see that the `number` variable in `_openchunk` and `_qfile` methods is static. Making it `self.number` would solve the issue

**Comment by peter-wangxu** [comment]
If you share file among multiple queue object, you have to lock the queue file on the disk with `flock`, otherwise, your queue may point at already-removed file, check it here:
```python
    def _clear_tail_file(self):
        """Remove the tail files whose items were already get."""
        tnum, _, _ = self.info['tail']
        while tnum >= 1:
            tnum -= 1
            path = self._qfile(tnum)
            if os.path.exists(path):
                os.remove(path)
            else:
                break
```

how is your use case?

**Comment by varungujarathi9** [comment]
Hello Thank you for your response

I am using the library for storing frames coming from my IP based CCTV
cameras. I have multiple cameras and would be creating an queue object for
each camera, now it should create and read frame from explicit queue files
created for each camera object.

Eg: Camera 1 should produce/consume from file q00001 & Camera 2 should read
and write from q00002. But it seems that both Camera 1 & 2 are reading and
writing from q00002.

---
Varun Gujarathi
Mob. No 8446025911

**Comment by peter-wangxu** [comment]
The reason why different queues(start from same path i suppose) are reading/writing same qfile is that, they share a same `info` file, so I guess you want have a separate `info`?

possible to have 2 separate queue object from different path for you 2 camera?

**Comment by varungujarathi9** [comment]
Solved!!

I just basically gave different paths in constructors for different cameras.
Thanks a lot!!

---
Varun Gujarathi
Mob. No 8446025911

**Comment by peter-wangxu** [comment]
Great!
