### ISSUE TITLE
Any plan to support dict api?

### ISSUE THREAD

**Issue by Cologler** [peter-wangxu/persist-queue#128]
Any plan to support them in the future?

https://github.com/peter-wangxu/persist-queue/blob/54bf1c2e90095fbf1595791ef9034d1bd211c4e4/persistqueue/tests/test_pdict.py#L16-L24

I can make a pull request.

**Comment by peter-wangxu** [comment]
@Cologler please go ahead sending out the PR!

**Comment by Cologler** [comment]
I found https://github.com/RaRe-Technologies/sqlitedict.
