### ISSUE TITLE
nack option - end of queue

### ISSUE THREAD

**Issue by imidoriya** [peter-wangxu/persist-queue#129]
It would be nice if there was an option for nack that sent it to the end of the queue.  Right now I'm doing an ack and doing another put, which may be what you would do internally, but anyway, figured I'd ask.  I'm running into the issue of a job failing and then it just continues to retry the same job over and over with a nack, failing each time.  After so many tries, I'll probably do a ack_failed, but for now I don't want it to hold up other jobs.

**Comment by peter-wangxu** [comment]
Can this be fulfilled by `ack_failed` followed by a `put`?

**Comment by imidoriya** [comment]
I expect so - I'm doing it now with an ack followed by a put.  What's the difference with the ack and ack_failed?  Is it just a status difference? I run `clear_acked_data` after each job to delete acks, so not sure of the difference.  Essentially, I just want it to try again later and move it to the back of the line.  Just wasn't sure if there was a cleaner way to do it than creating a new job.

As a side question, sometimes the qsize lists `-1` after jobs complete.  Why is that?  Shouldn't the min be 0?

**Comment by imidoriya** [comment]
This would just be a on option of efficiency, but one method would be to have the self._select() ORDER BY timestamp ASC and then have an option to update the timestamp on nack.  This would essentially put it to the back of the queue. Might need to create an index on timestamp.

**Comment by imidoriya** [comment]
What might be better is a way to go to the "next" job in the queue.  Then you wouldn't have to put anything to the back.

Right now, it's goes like this.
```py
ackq.put('str1')
ackq.put('str2')
ackq.put('str3')
item = ackq.get()
print(item)
str1
ackq.nack(item)
item = ackq.get()
print(item)
str1
```
I don't know how to move forward and get the next one.  This is particular needed when I'm trying to get a certain type of job if I have multiple job types that can run at the same time.  I have to ack_failed / put 10,000 jobs to get to 50 jobs of another type.  Which is really confusing in a multithread situation where another thread is working on those 10,000 jobs.

You can get the next item by doing another `get()`, but that doesn't release the last one.  If you `get()` and then `nack()`, your next `get()` will go back to the original - it always starts at 0.  

It would be great to have some method of this.. 
```py
ackq.put('str1')
ackq.put('str2')
ackq.put('str3')
item = ackq.next()
print(item)
str1
ackq.nack(item)
item = ackq.next()
print(item)
str2
```
