### ISSUE TITLE
.get() hangs when queue is empty

### ISSUE THREAD

**Issue by ghost** [peter-wangxu/persist-queue#138]
persist-queue 0.5.0 on JupyterLab 2.2.4 on Python 3.7.6 on macOS 10.15.6

```
q = persistqueue.Queue('queue', autosave=False)
q.get()
```
^ this just hangs

```
while q.empty() is False:
    task = q.get()
    print(task)
    q.task_done()
    
print("all done")
```
^ used that as a workaround, but I thought you should know. 

`queuelib` returns `None` when popping an empty q

**Comment by peter-wangxu** [comment]
The default behavior is to block, you can specify timeout=0 parameter for the purpose
