### ISSUE TITLE
qsize() reports negative value

### ISSUE THREAD

**Issue by imidoriya** [peter-wangxu/persist-queue#144]
Using the SQLiteAckQueue multithreaded and I'm trying to get a count on the queue size using qsize(), but sometimes I'll see negative numbers. I think that the issue is the `_unack_cache`  is not included in the total queue size, which I think it probably should be as it hasn't yet received an `ack/task_done`  So in a mutlithreaded situation where you have 10 get calls, you're going to report a queue size 10 less than what actually exists, since those jobs haven't been completed.

This also causes an ever changing qsize as things can be `get`/`nack` regularly, so the size keeps going up and down as the state changes.  I think it should only change the size when a new item is added `put` or an item is removed  `ack/ack_failed/task_done`.  I don't think a `get` or `nack` should change the reported size.

**Comment by mariansam** [comment]
Happens to me too.

Steps to reproduce:
```console
>>> from persistqueue import SQLiteAckQueue
>>> q = SQLiteAckQueue('db')
>>> q.put('a')
>>> item = q.get()
>>> # doing some hard work with the item; program suddenly crashes
```
(hit ctrl-d)
```console
>>> from persistqueue import SQLiteAckQueue
>>> q = SQLiteAckQueue('db')
resume 1 unack tasks
>>> q.qsize()
0
>>> q.get()
'a'
>>> q.qsize()
-1
```

**Comment by imidoriya** [comment]
@mariansam, I've just written my own call for the moment while this issue is under review by @peter-wangxu .  Maybe it will help you.
```
    def qsize(self, queue):
        return max(0, queue.qsize() + len(queue._unack_cache))
```

I can see where not including the `_unack_cache` might be the desired result, so I'm interested to hear Peter's thoughts.  In `sqlackqueue.py`, `qsize()` calls `self.size` which calls `self.total`.  So I think there is some room to have qsize() include the unack_cache, but calling size() or total() does not, giving options.

Right now, the qsize() just returns pending items and does not include those currently in-work.  That can become a problem if you're doing a lot of `get`/`nack`, because your qsize() is constantly bouncing up and down, even though the size of your queue hasn't really changed.  For my use which is a polling system, checking if something is completed or not, I want the queue size to only change when an item is added or completed (`acked`).
