### ISSUE TITLE
Suppress message "Default is not on the same filesystem with queue path .. "

### ISSUE THREAD

**Issue by bbookman** [peter-wangxu/persist-queue#145]
Just tried this library and I see the following:

`Default tempdir '/tmp/tmp_37pg8kl' is not on the same filesystem with queue path 'this_queue.txt',defaulting to 'this_queue.txt'.`

Other than trying to handle this oddly in my code, how might I suppress this message? IMO,  it is informative but perhaps should not be displayed unless there is an actual error

**Comment by peter-wangxu** [comment]
You can simply specify `tempdir=./` to suppress that
