### ISSUE TITLE
__str__ for Queue feature request

### ISSUE THREAD

**Issue by bbookman** [peter-wangxu/persist-queue#146]
I'm probably dumb, but for debugging I'd like to always see the entire queue.  Can you add an __str__ method to Queue please

**Comment by imidoriya** [comment]
I'm not the developer, but I think your request could use some clarification.  A queue would probably be a `list` of whatever you put in it (a `dict` in my case).  Not sure what adding a `str` method to the queue would actually do or what debugging it would give, perhaps the path to the file?

**Comment by bbookman** [comment]
i think i misunderstood the tool.  However, even though I could implement something in code where I "get" everything from the Queue without removing items, it would be a nice feature to add that to the core class.

**Comment by imidoriya** [comment]
If you're looking to get sort of the raw select results and loop through the items yourself, I did this recently.
```
rows = q._getter.execute(q._sql_select)
for row in rows:
    item = q._serializer.loads(row[1])
    print(item)
```
