### ISSUE TITLE
Permanent removal from queue?

### ISSUE THREAD

**Issue by bbookman** [peter-wangxu/persist-queue#147]
Again, I'm dumb and new to queuing.  Exactly how do I REMOVE something from the queue.  task_done does not seem to do it either..

```
from persistqueue import Queue
q = Queue("my_test")
q.put('a')
q.put('b')
print(q.get())
q = Queue("my_test")
print(q.get())
print(q.get())
print(q.get())
```

```
a
a
b
a
```

```
from persistqueue import Queue
q = Queue("my_test")
q.put('a')
q.put('b')
print(q.get())
q.task_done()
print(q.get())
q.task_done()
print(q.get())
q.task_done()
print(q.get())
```

```
a
b
a
b
```

**Comment by bbookman** [comment]
```del q ``` does not seem right either

```
from persistqueue import Queue
q = Queue("my_test")
q.put('a')
q.put('b')
print(q.get())
print(q.get())
del q
q = Queue("my_test")
print(q.get())
print(q.get())
```
```
b
a
b
a
```

**Comment by bbookman** [comment]
This just does not seem true, again though - i'm dumb

> By default, items added to the queue are persisted during the put() call, and **items removed from a queue are only persisted when task_done()** is called

**Comment by bbookman** [comment]
I want to remove a **single item** from the queue.  I'm confused

**Comment by imidoriya** [comment]
I haven't used the base `Queue` very much, but I use the `SQLiteAckQueue` and I `ack` completed items, which removes them.  Then you can run `clear_acked_data` if you want to delete the historical `acked` items.

**Comment by peter-wangxu** [comment]
```python
from persistqueue import Queue
q = Queue("my_test")
q.put('a')
q.put('b')
print(q.get())
print(q.get())
q.task_done() # this is what you missed
del q
q = Queue("my_test")
print(q.get()) # this will block the q.get()
print(q.get())
```

**Comment by peter-wangxu** [comment]
@bbookman see my code snippet

**Comment by bbookman** [comment]
Thank you so much!  I'll give this a shot in my code.

**Comment by bbookman** [comment]
Sorry, I really am missing something

```
from persistqueue import Queue
q = Queue("my_test")
q.put('a')
q.put('b')
print(q.get()) # b
print(q.get()) # a
q.task_done() 
del q.  # should delete the queue - right???
q = Queue("my_test")
print(q.get())   # nothing should be in the queue... but prints "b"
print(q.get()) # nothing should be in the queue ... but prints "a"
```
```
b
a
b
a
```

Note these messages, in case they shed light on what is happening

```
Default tempdir '/tmp/tmp5m0701jr' is not on the same filesystem with queue path 'my_test',defaulting to 'my_test'.
Default tempdir '/tmp/tmp_id6omj_' is not on the same filesystem with queue path 'my_test',defaulting to 'my_test'.
```

**Comment by bbookman** [comment]
Another oddity...  I assumed these messages about **default tempdir** mean that a **default** file is created if you do not give Queue an argument...  but

```
<ipython-input-2-7c64a5f11e85> in <module>
      1 from persistqueue import Queue
----> 2 q = Queue()
      3 q.put('a')
      4 q.put('b')
      5 print(q.get()) # b

TypeError: __init__() missing 1 required positional argument: 'path'
```

**Comment by bbookman** [comment]
Looks like I had something in memory/cache.  It works as described.  Sorry.
```
from persistqueue import Queue
q = Queue('tmp')
q.put('a')
q.put('b')
print(q.get()) # b
print(q.get()) # a
q.task_done() # this is what you missed
del q
q = Queue('tmp')
print(q.get()) # this will block the q.get()
print(q.get())```

```
Default tempdir '/tmp/tmpor0fp0jy' is not on the same filesystem with queue path 'tmp',defaulting to 'tmp'.
Default tempdir '/tmp/tmpzg_oz_x_' is not on the same filesystem with queue path 'tmp',defaulting to 'tmp'.
a
b
```
