### ISSUE TITLE
Queue Item Metadata

### ISSUE THREAD

**Issue by imidoriya** [peter-wangxu/persist-queue#149]
If I do a `queue.get()`, it gives me the data in the queue, but there is metadata with items such as the id, timestamp, and status.  I'd like to be able to read the timestamp.  Is there an easy way to do that when I get() a queue item?  Thanks

**Comment by ElusiveTau** [comment]
There is a conceptual problem with your question: why should the queue care about the metadata of the items it stores?

**Comment by jeffg2k** [comment]
Had I been forward thinking, I might have added my own timestamp to the data itself, but I'm trying to know when a job was created so that I can expire them after a period of time.

**Comment by imidoriya** [comment]
Yeah, that's what I was thinking too.

**Comment by kstratis** [comment]
I second that.

I think the ideal thing to go for would be to return a metadata hash (or just an id) each time we place something in the queue. This is usually called "job id" which in this case could be replaced with sqlite's `_id` field.

Such a solution would also pave the way for more advanced functionality like deleting an unprocessed item from the queue or even updating its data.

What do you @peter-wangxu? Would that be easy to do?
