### ISSUE TITLE
Why is  _MAX_ACKED_LENGTH Hardcoded?

### ISSUE THREAD

**Issue by cnrmck** [peter-wangxu/persist-queue#150]
In this code, _MAX_ACKED_LENGTH is hardcoded:
https://github.com/peter-wangxu/persist-queue/blob/5ce10afcfcd81afd46a9eae32ba085d8ae900240/persistqueue/sqlackqueue.py#L35

Why is it hardcoded to 1000? I need to remove about 10 to 100 thousand acked entries each time I run this, is there any reason I shouldn't change _MAX_ACKED_LENGTH to 100_000 and then run that?

**Comment by cnrmck** [comment]
Related to https://github.com/peter-wangxu/persist-queue/issues/126

**Comment by peter-wangxu** [comment]
Currently, the `clear_acked_data` only delete 1000 at max each time, `VACCUM` usually dost NOT take too much difference.

**Comment by cnrmck** [comment]
@peter-wangxu Thank you for the response. Why does `clear_acked_data` only delete 1000 at a time? 

Is there a way I could fix this? I'm happy to contribute this is a pretty important requirement for me.

**Comment by peter-wangxu** [comment]
> @peter-wangxu Thank you for the response. Why does `clear_acked_data` only delete 1000 at a time?
> 
> Is there a way I could fix this? I'm happy to contribute this is a pretty important requirement for me.

You can look around the function `clear_acked_data` at https://github.com/peter-wangxu/persist-queue/blob/32acfdecf2dad5f286139ce7dc4e6202b0bcae50/persistqueue/sqlackqueue.py#L114
