### ISSUE TITLE
Does this not work between simultaneous python processes?

### ISSUE THREAD

**Issue by bradmorg** [peter-wangxu/persist-queue#152]
Hello,

If I open two python IDLE sessions, they cannot work from the same queue.  Is that working as intended?

Also for SQLite - is there any documentation for how to create the database? A quickstart guide would be helpful.

Thanks.

**Comment by peter-wangxu** [comment]
> Also for SQLite - is there any documentation for how to create the database? A quickstart guide would be helpful.



> Hello,
> 
> If I open two python IDLE sessions, they cannot work from the same queue. Is that working as intended?

Yes, working for multi-threading, not multi-process
> Also for SQLite - is there any documentation for how to create the database? A quickstart guide would be helpful.

Just follow https://github.com/peter-wangxu/persist-queue#example-usage-with-a-sqlite3-based-queue
> Thanks.
