### ISSUE TITLE
SQLiteQueue put_nowait and get_nowait

### ISSUE THREAD

**Issue by Yomguithereal** [peter-wangxu/persist-queue#155]
Hello @peter-wangxu,

To remain consistent with python's `queue`, it could be useful to also have a `#.put_nowait` and `#.get_nowait` on the `SQLiteQueue`. I can open a PR to add them but I need to check with you whether this makes sense or not. Indeed, it seems the `#.put` method has no `block` kwarg because it has to block?

**Comment by Yomguithereal** [comment]
Ok, I understand that `#.put_nowait` does not really make sense because the sqlite queue cannot have a `maxsize`. In this case, should `SQLiteQueue.put_nowait` just be an alias of the `#.put` method? Or is this potentially confusing to users and should be avoided. On my end, this would make some third-party code relying on python queue interface more easy to use.

**Comment by peter-wangxu** [comment]
I agree that persist-queue should make the be to keep compatibility with the standard queue api.

**Comment by Yomguithereal** [comment]
Thanks for merging the PR @peter-wangxu. What's your take regarding `#.put_nowait`?

**Comment by peter-wangxu** [comment]
same point, please go ahead. happy to see that PR

**Comment by Yomguithereal** [comment]
My point is I am not sure how to implement the method in the case of the `SQLiteQueue` because the `#.put` method does not accept a `block` kwarg (which is expected since the queue does not accept a `maxsize` kwarg so it cannot be full). So should it just be an alias (all while adding a noop `block` kwarg to `#.put`) of `#.put`? Or is this maybe introducing some confusion for the users?

**Comment by Yomguithereal** [comment]
In any case, I opened a PR illustrating what I mean.
