### ISSUE TITLE
mySQL db

### ISSUE THREAD

**Issue by KillahB33** [peter-wangxu/persist-queue#173]
I saw you mention in another issue that moving to an external database such as mysql would fix some issues with access a queue from multiple machines.
I currently have a Docker setup with two containers in one pod and I can post to the queue but my other container doesn't appear to be updating it's count for the queue, I switched to ack queue and it's still doesn't appear to be working.
So I am hoping if I switch to an external db such as mySQL/MariaDB that this issue would be fixed, just need to know the syntax for using that instead of SQLlite

**Comment by peter-wangxu** [comment]
> Sorry to bug you @peter-wangxu but I am at the stage where I need to make this work or move on but don't want to spend time rewriting to use an mqtt if this can be made to work with a small change.

not very big change, i could try to give a version this weekend.

**Comment by peter-wangxu** [comment]
> Found it. Here is someone else with the issue. https://stackoverflow.com/questions/60276355/why-python-script-loop-is-not-fetching-updated-data-from-db
> 
> I updated my code to count the records from the db instead of queue size, and without conn.commit() the count wasn't updating either but as soon as I do conn.commit() after execute it started working properly.

Thanks for the investigation. i was busy with other stuff, will continue work on this later this weekend
