### ISSUE TITLE
sqlite vacuum not working

### ISSUE THREAD

**Issue by mo-pyy** [peter-wangxu/persist-queue#183]
I use SQLiteAckQueue with multithreading

I periodically run `queue.clear_acked_data()` and `queue.shrink_disk_usage()`.
It does not change the queue db file size. 

When I run VACUUM with sqlite3 manually, the file size shrinks very much.

**Comment by peter-wangxu** [comment]
> SQLiteAckQueue

What's the version of persist-queue and python?

**Comment by mo-pyy** [comment]
persist-queue is v0.7.0 and python is 3.6.9

**Comment by peter-wangxu** [comment]
Please give a try with v0.8.0beta, it should fix the issue

**Comment by mo-pyy** [comment]
I tried v0.8.0beta, and now the file size shrinks, but only after the program finished execution. The problem is, that I need to shrink the size continuously without stopping the application.

**Comment by peter-wangxu** [comment]
> I tried v0.8.0beta, and now the file size shrinks, but only after the program finished execution. The problem is, that I need to shrink the size continuously without stopping the application.

A workaround is to close the connection with `del queue`

**Comment by mo-pyy** [comment]
Thanks, after closing the DB it seems to shrink.

But closing the connection with `del queue` is not clean and leads to occasional `sqlite3.OperationalError: disk I/O error` errors. Now im closing by running
```python
q._putter.close()
q._getter.close()
del q
```
Could you expose a public method that closes these connections, because I should not mess with the internals?

**Comment by peter-wangxu** [comment]
Possible that you submit a pr for this?

> Thanks, after closing the DB it seems to shrink.
> 
> 
> 
> But closing the connection with `del queue` is not clean and leads to occasional `sqlite3.OperationalError: disk I/O error` errors. Now im closing by running
> 
> ```python
> 
> q._putter.close()
> 
> q._getter.close()
> 
> del q
> 
> ```
> 
> Could you expose a public method that closes these connections, because I should not mess with the internals?

**Comment by peter-wangxu** [comment]
fixed in https://github.com/peter-wangxu/persist-queue/pull/197
