### ISSUE TITLE
Queue items not removed after each get()

### ISSUE THREAD

**Issue by rayosborn** [peter-wangxu/persist-queue#184]
This issue is obviously related to #176, but that issue focused on SQL databases whereas this concerns file-based queues. The issue is, however, the same, i.e., that items remain on the queue even after they are retrieved with a call to `get()`. By serializing the queue with JSON, it is possible to directly view the contents of the queue, which explicitly shows that items remain on the queue, after a call to `queue.get()`, whether the queue is initialized with `autosave=True` or `queue.task_done()` is called. Items are only retrieved once, but that is presumably because the `info` file stores the pointer to the next item. 

Here is some test code:
```
import argparse
from persistqueue import Queue
from persistqueue.serializers import json


def main():

    parser = argparse.ArgumentParser(description="Test file-based queue")

    parser.add_argument(
        "-w", "--write", type=str, help="text to write to the queue"
    )
    parser.add_argument(
        "-r",
        "--read",
        action="store_true",
        help="read the next item on the queue",
    )

    args = parser.parse_args()

    queue = Queue("task_queue", serializer=json, autosave=True)
    if args.write:
        queue.put(args.write)
    if args.read:
        print(queue.get(timeout=0))
        queue.task_done()


if __name__ == "__main__":
    main()
```
When this script is run, the items are written to the JSON file and retrieved exactly as expected.
```
$ python testqueue.py -w item1
$ python testqueue.py -w item2
$ python testqueue.py -w item3
$ python testqueue.py -r
item1
$ python testqueue.py -r
item2
$ python testqueue.py -r
item3
```
However, the contents of the file `task_queue/q00000` is still the following at the end of these commands, i.e., the queue is not empty, even though another call to `python testqueue.py -r` will trigger a `persistqueue.exceptions.Empty` exception. 
```
$ cat task_queue/q00000 
"item1"
"item2"
"item3"
```
In my use of `persistqueue`, it would be important to remove each line returned by a call to `get()`. Is there a way to accomplish this? 

I am running v0.7.0 on Python 3.8.12.

**Comment by rayosborn** [comment]
After a little investigation, I see that it is possible to roughly get what I want by reducing `chunksize` to 1. Then, each item is stored in a separate file, which is removed after the corresponding call to `queue.get()`.  Since I want to write a function to interrogate what is currently in the queue, this is a little more cumbersome than I would like, but it is at least functional. It would be useful if the documentation contained a brief description of what this parameter means. The only description in the docstring is that it determines how many entries are in each chunk file, but there is no discussion of the implications of changing the number. Is this a trade-off between efficiency and reducing race conditions? Does choosing a value of 1 have any drawbacks, apart from increasing the number of file openings? My queues should not get too large, so this isn't such an important issue for my use case.

**Comment by peter-wangxu** [comment]
By default, every `chunksize=100` items stores in a single data file, when all items were get by `get`, the task_done will remove the tailf file from filesystem. setting chunksize to 1 is not recommendable( since it's inefficient to remove a file on each `get`), but workable for your case.

**Comment by rayosborn** [comment]
Thanks. I have found that one nice feature is that I can instantiate the queue with `autosave=False` in order to list all the queue items, and then with `autosave=True` to use the queue as a FIFO. It's a useful package. If you want to close this issue, that's fine by me. My only suggestion is that it would be useful to add comments to the documentation about the queue items only being deleted after each chunk is completed.
