### ISSUE TITLE
What if data is already serialized

### ISSUE THREAD

**Issue by dineshbvadhia** [peter-wangxu/persist-queue#187]
Wrt file-based queues, if the data items for `q.put(item)` are already serialized (in my case, with json or msgpack) then what are the options with persist-queue ?

**Comment by peter-wangxu** [comment]
persist-queue supports both, either raw object or serialized. you can choose based on your needs

**Comment by dineshbvadhia** [comment]
Looking at the code, raw = True|False is available in the sql get/put functions but not for file-based queues ?
