### ISSUE TITLE
What if data is already serialized Part II ?

### ISSUE THREAD

**Issue by dineshbvadhia** [peter-wangxu/persist-queue#188]
Looking at the code, raw = True|False is available in the sql get/put functions but not for file-based queues or did I miss something ?

_Originally posted by @dineshbvadhia in https://github.com/peter-wangxu/persist-queue/issues/187#issuecomment-1249498019_

**Comment by peter-wangxu** [comment]
When Raw=True, we return the internal the primary key id and timestamp along with the data
```python
                        return {
                            'pqid': row[0],
                            'data': item,
                            'timestamp': row[2],
                        }
```

while for file based queue, 
the item is also stored as it is, no extra metadata store in local file.
