### ISSUE TITLE
Thread safe for putting, how about getting?

### ISSUE THREAD

**Issue by qingfeng0820** [peter-wangxu/persist-queue#19]
https://github.com/peter-wangxu/persist-queue/blob/10f7ec73812b92115e4e574a0fb1e5fcb59bc127/persistqueue/sqlbase.py#L14

**Comment by peter-wangxu** [comment]
This is an issue in current implementation,
the `_pop` is not atomic, so duplicate item can be fetched by different threads.

https://github.com/peter-wangxu/persist-queue/blob/10f7ec73812b92115e4e574a0fb1e5fcb59bc127/persistqueue/sqlqueue.py#L39

**Comment by peter-wangxu** [comment]
@qingfeng0820 will you push a fix for this?

**Comment by qingfeng0820** [comment]
Ok

**Comment by peter-wangxu** [comment]
Should be fixed in https://github.com/peter-wangxu/persist-queue/pull/20

Closing this now.
