### ISSUE TITLE
FILOSQLiteAckQueue is not exported from __init__

### ISSUE THREAD

**Issue by Yomguithereal** [peter-wangxu/persist-queue#195]
Hello @peter-wangxu,

The `FILOSQLiteAckQueue` is not exported from the package `__init__` file. It can still be imported from `persistqueue.sqlackqueue`.

Is this because it is not safe to use? Or is it just because it was forgotten to add it? In which case I can provide a PR to do so if you want.

It may be related but it seems to me the `_SQL_SELECT_WHERE` of `FILOSQLiteAckQueue` is not present, and therefore incorrect. But I don't really know if this is still used by the base to perform anything meaningful in the context of an ack queue.

**Comment by peter-wangxu** [comment]
1. please submit a PR for exporting FILOSQLiteAckQueue
2. seems the _SQL_SELECT_WHERE is never used by ACK queue

**Comment by Yomguithereal** [comment]
@peter-wangxu I have opened the PR #196 as requested. I also exported `AckStatus`. Tell me if this is ok.
