### ISSUE TITLE
AttributeError: module 'persistqueue' has no attribute 'MySQLQueue'

### ISSUE THREAD

**Issue by psagarna** [peter-wangxu/persist-queue#198]
import persistqueue 

db_conf = {
....
}
q = persistqueue.MySQLQueue(name="test",**db_conf)
q.put('str1')
q.put('str2')
q.put('str3')
q.get()

output:
AttributeError: module 'persistqueue' has no attribute 'MySQLQueue'
(pqueue)

**Comment by psagarna** [comment]
from persistqueue import MySQLQueue

db_conf = {
....
}
q = persistqueue.MySQLQueue(name="test",**db_conf)
q.put('str1')
q.put('str2')
q.put('str3')
q.get()

output:
AttributeError: module 'persistqueue' has no attribute 'MySQLQueue'
(pqueue)

**Comment by psagarna** [comment]
pip install persist-queue[extra]

**Comment by peter-wangxu** [comment]
what's the version installed?
