### ISSUE TITLE
In-Memory Database Issues

### ISSUE THREAD

**Issue by ztgrace** [peter-wangxu/persist-queue#22]
Cool, project! I've incorporated it into [changeme](https://github.com/ztgrace/changeme) and was looking at switching the disk-based FIFO queue to be an in-memory queue. It looks like you've got some code indicating you're interested in supporting an in-memory database but when I tried it out, I have run into a few bugs:

## :memory: Directory Gets Created
The first issue I noticed was that when specifying `:memory:` as a path the code actually creates that directory. Test code:

    >>> from persistqueue import FIFOSQLiteQueue
    >>> q = FIFOSQLiteQueue(path=":memory:", multithreading=True, name='test')

Results:

    # file \:memory\:/
    :memory:/: directory

This can be fixed by adding a second condition to line [74](https://github.com/peter-wangxu/persist-queue/blob/10b8fa0e8bf5da6d44dbeb85f94a2b0779685d41/persistqueue/sqlbase.py#L74) of sqlbase.py:

    @@ -71,7 +71,7 @@ class SQLiteBase(object):

         def _init(self):
             """Initialize the tables in DB."""
    -        if not os.path.exists(self.path):
    +        if not os.path.exists(self.path) and not self.path == self._MEMORY:
                 os.makedirs(self.path)
             log.debug('Initializing Sqlite3 Queue with path {}'.format(self.path))

## No Such Table

After fixing the `:memory:` path issue, it looks like the table's not getting created correctly.

    >>> from persistqueue import FIFOSQLiteQueue
    >>> q = FIFOSQLiteQueue(path=':memory:', multithreading=True, name='test')
    >>> q.put('foo')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "persistqueue/sqlqueue.py", line 36, in put
        self._insert_into(obj, _time.time())
      File "persistqueue/sqlbase.py", line 20, in _execute
        obj._putter.execute(stat, param)
    sqlite3.OperationalError: no such table: queue_test

I haven't had a chance to track this bug down, but thought I'd let you know.

Cheers,
Zach

**Comment by peter-wangxu** [comment]
Hi Zach,
Thanks for using and reporting this bug, I will investigate and fix them in a later patch.

Thanks
Peter

**Comment by peter-wangxu** [comment]
Fixed in version https://github.com/peter-wangxu/persist-queue/releases/tag/v0.3.1

**Comment by peter-wangxu** [comment]
just FYI
I also filed a bug/query for adding a more power in-memory sqlite support: https://github.com/ghaering/pysqlite/issues/118
