### ISSUE TITLE
FIFOSQLiteQueue: the get() method returns None instead of blocking

### ISSUE THREAD

**Issue by delica1** [peter-wangxu/persist-queue#24]
and if I specify get(block=True) it raises the empty exception

**Comment by peter-wangxu** [comment]
Hi how is your script?

When you create the queue with `auto_commit=False`, you need to call `queue.task_done()` to persist the change to disk.

alterlatively, you can set `auto_commit=True`, then you code should work as expect.

I also plan to change the default to `auto_commit=True` to keep the default behavior as of before `v0.3.0`
Thanks
Peter

**Comment by peter-wangxu** [comment]
It's all set in version v0.3.1 now.

**Comment by delica1** [comment]
Update: even with a timeout of 1000, I still get the "database is locked"
error. Not sure right now if the SD card is really that slow or if it's a
bug.

**Comment by peter-wangxu** [comment]
I did have a Pi 3B before with a class 10 SD card:)

Did you have a change to run the benchmark script: https://github.com/peter-wangxu/persist-queue#benchmark

You may need to choose which queue to use on the Pi.

**Comment by peter-wangxu** [comment]
BTW, you can try the file based queue for your case: https://github.com/peter-wangxu/persist-queue#example-usage-with-a-file-based-queue

**Comment by delica1** [comment]
They're quite nice little machines :) low power and fairly capable. I am
also using a class 10 SD card btw.

I tried the file based queue and this works fine, with no errors, but is
very slow. I was hoping the sql based queue might be faster, but it gives
me errors. I might later try attaching a USB stick and storing the DB on
it. Could be that the access speeds are better off a USB stick :)

But you're right, I will switch to using the file based queue for now, as
this works well! Thanks again!

**Comment by peter-wangxu** [comment]
@delica1 I did a commit to speed up the sqlite3 overall performance via WAL. you can try it in your Pi3 now:)

**Comment by delica1** [comment]
Thank you Peter! Much appreciated. On vacation from tomorrow but will try
when I am back :)
