### ISSUE TITLE
Request to fork and use persist-queue in task queue implementation.

### ISSUE THREAD

**Issue by jaytheking** [peter-wangxu/persist-queue#33]
I've been working on a similar project as this to create a task queue based on sqlite3, i found your project actually covers all my use cases for the queue part and don't want to re-implement largely the same functionality. 

I want to ask permission to fork your repo and start integrating the server and workers component.

**Comment by peter-wangxu** [comment]
@jaytheking 

Forking is always welcomed, nobody can stop that:). please go ahead your work then.

BTW, you may decide to incorporate the source code into your project tree or simple set persist-queue as dependency, under both situations, I hope that found fixes can be ported to persist-queue as well thus benefiting the users of persist-queue.


Thanks
Peter

**Comment by jaytheking** [comment]
Cheers, I just thought a heads up would be polite.
