### ISSUE TITLE
Queue size

### ISSUE THREAD

**Issue by Markkeli** [peter-wangxu/persist-queue#35]
Hi,

Thank you for this great contribution! I was wondering whether there is any way to limit the queue size?

**Comment by peter-wangxu** [comment]
The answer is YES and NO

the file based provides a `maxsize` parameter, while the sqlite based doesn't.

**Comment by Markkeli** [comment]
Is there any way to get information of the sqllite based queue size?

**Comment by peter-wangxu** [comment]
`queue.qsize()` will do the trick.

Thanks
Peter

**Comment by Markkeli** [comment]
Many thanks for your answers, Peter! One more question: does the qsize return the number of items in the queue or the size by some different measure?

**Comment by peter-wangxu** [comment]
it returns the count of remaining items

**Comment by peter-wangxu** [comment]
Question answered, closing it now.
