### ISSUE TITLE
task_done not behaving as I would expect

### ISSUE THREAD

**Issue by jamesporritt** [peter-wangxu/persist-queue#36]
I've been playing with both the file and sqlite based queues. My understanding with both is that you can put items to the queue, you can get items, but only when you do a 'task_done' (per item in the case of the file based queue or once in the case of the sqlite based queue) does the item get removed. I could therefore 'get' what I like from the queue, but if I never did a task_done, I could kill my app, restart and all the items would still be there.  (i.e. all the items that were put there originally) My experience of putting 10000 items and doing some 'get's without 'task_done' and then restarting is thus:

**Queue**: I'll get something like the following when I restart: 
 $python streamer.py 
Traceback (most recent call last):
...
  File ".../lib/python2.7/site-packages/persistqueue/queue.py", line 57, in __init__
    self.tailf = self._openchunk(tnum)
  File ".../lib/python2.7/site-packages/persistqueue/queue.py", line 192, in _openchunk
    return open(self._qfile(number), mode)
IOError: [Errno 2] No such file or directory: '/var/tmp/queue/q00005'

**SQLiteQueue**: I initialise the queue with auto_commit=False, I consume many items and even though I never call task_done, the items I 'get' are no longer on the queue when I restart the script. (I would expect them all to still be there)

Please advise.

**Comment by jamesporritt** [comment]
So, with Queue, you would have two tails, a hard tail (marking the physical end of queue) and a soft tail (marking the next item to 'get'). The hard tail (so, self.info['tail']) would be manipulated by task_done. The soft tail would be manipulated by get and handle reading from the file pointers. I'll see if I can implement this.

**Comment by peter-wangxu** [comment]
Thanks for the exploration.

I did a quick check for the SQLiteQueue, it's probably cause by a database commit caused by the sqlite3, I will need to investigate how to avoid this.

**Comment by peter-wangxu** [comment]
@jamesporritt You can give a try for above fix, it addresses the issue you mentioned both for file and sqlite queue.
