### ISSUE TITLE
Performance Comparison with DiskCache

### ISSUE THREAD

**Issue by grantjenks** [peter-wangxu/persist-queue#38]
Hi there -- author of python-diskcache here. I wonder what the performance of these two projects is like. DiskCache implements the collections.deque interface rather than queue.Queue but they are similar enough.

You may be curious to see the diskcache source for some speedup ideas. For example, you could go a bit faster with a higher pickle protocol version.

If you create a benchmark then please share results. I think your file-based Queue implementation may be faster.

**Comment by peter-wangxu** [comment]
Thanks for sharing your idea, i will take a look of your implementation.

I did a simple run locally:

```python
In [1]: from persistqueue import SQLiteQueue

In [2]: q = SQLiteQueue('/tmp/sql', auto_commit=False)
auto_commit=False is still experimental,only use it with care.

In [3]: q.put('111')

In [4]: %timeit -n 1 -r 1 q.get()
1 loop, best of 1: 181 µs per loop

In [5]: from persistqueue import Queue

In [6]: q2 = Queue('/tmp/compare/')

In [7]: q2.put(111)

In [8]: %timeit -n 1 -r 1 q2.get()
1 loop, best of 1: 114 µs per loop

In [9]: %timeit -n 1 -r 1 q2.put(222)
1 loop, best of 1: 749 µs per loop

In [10]: %timeit -n 1 -r 1 q.put(222)
1 loop, best of 1: 10.8 ms per loop

```

Previously, i did some profiling, the bottlenecks are writing to and reading from disk, merely the pickle part.


Thanks
Peter

**Comment by grantjenks** [comment]
Interesting. I did some similar profiling. Here's what I saw:

```
In [1]: from persistqueue import Queue

In [3]: q1 = Queue('/tmp/pq/queue')

In [10]: %timeit -n 1000 -r 5 q1.put(b'0123456789')
1000 loops, best of 5: 251 µs per loop

In [11]: %timeit -n 1000 -r 5 q1.get()
1000 loops, best of 5: 11 µs per loop

In [16]: from diskcache import Deque

In [17]: d = Deque(directory='/tmp/dc/deque')

In [20]: %timeit -n 1000 -r 5 d.append(b'0123456789')
1000 loops, best of 5: 152 µs per loop

In [21]: %timeit -n 1000 -r 5 d.popleft()
1000 loops, best of 5: 144 µs per loop
```

The Deque.popleft() operation is much slower than your Queue.get() because diskcache is both thread-safe and process-safe. So while Queue.get can avoid writes to disk, Deque.popleft cannot.

**Comment by peter-wangxu** [comment]
The `Deque.append` is around 2 times faster than Queue, it's worth trying a higher pickle.

Curious about how you achieve process-safe, basically, i think a call like `fcntl.lockf` is required:)

**Comment by grantjenks** [comment]
DiskCache uses SQLite for transactions. It's process-safe and cross-platform; probably uses fcntl.lockf under the hood.
