### ISSUE TITLE
Unique items only (no duplicates) 

### ISSUE THREAD

**Issue by delica1** [peter-wangxu/persist-queue#39]
Not an issue but wasn't sue where to post this. Would it be possible to implement a queue that allows no duplicate items? Kind of like a set. On second thought it could be an option for the existing queue implementation too. I would try to add it locally for me but not sure how to check if an item already exists in the queue!

**Comment by peter-wangxu** [comment]
Make sense to create a `set` like queue for your use case.

How is your data? Is it hashable?

**Comment by delica1** [comment]
Yes, it's strings!

**Comment by peter-wangxu** [comment]
Did you use the file based queue or sqlite based queue?

On my first thought, storing the hash value in sqlite as a column is possible, we can check the uniqueness via SQL, but for filed based queue, no idea for now.

Do you have any idea?

**Comment by delica1** [comment]
I'm using the file based queue, but will try the SQL one again later today.
If I remember correctly my issue was that the get() call was not blocking,
but was timing out and I think this behaviour has now been changed.

The way I envisioned this to work was by implementing the __contains__
method. So if I type

"string" in p_queue

I will get a True or False. And then based on the same method, the new
value can be added or discarded if it is already in the queue. I haven't
really looked how you implemented the file based queue so I cannot suggest
anything useful there. Anyhow, I will look later if the SQL queue works for
me now, and will let you know.

Almir

**Comment by delica1** [comment]
The SQL based queue works great for me right now! - I just switched
completely from the file based queue. Anyhow, if you think the
"non-duplicate allowing queue" is useful and want to implement it, that
would be fantastic. Otherwise if you think this is too specific to my case,
I can probably override the __contains__ method myself as well.

Almir

**Comment by peter-wangxu** [comment]
That's a good news.

A `set` like queue can be useful in many cases. I do support adding this:

- it can be a new queue, say it's `SetQueue`, we can optimize it on demand
- either, doing as you mentioned.

Although, I prefer the first one, the second option is also welcome.
Do you mind sending out the PR for either solution?

Thanks
Peter

**Comment by delica1** [comment]
I don't know how to do a pull request but this should work:

```
class UniqueQ(persistqueue.SQLiteQueue):
    _TABLE_NAME = 'unique_queue'
    _SQL_CREATE = ('CREATE TABLE IF NOT EXISTS {table_name} ('
                   '{key_column} INTEGER PRIMARY KEY AUTOINCREMENT, '
                   'data BLOB, timestamp FLOAT, UNIQUE (data))')

    def put(self, item):
      obj = pickle.dumps(item)
      try:
        self._insert_into(obj, _time.time())
      except sqlite3.IntegrityError as e:
        #print("UNIQUE constraint failed:")
        pass
      else:
        self.total += 1
        self.put_event.set()
```

**Comment by delica1** [comment]
This works for me but can't fully test right now.

```
class UniqueQ(persistqueue.SQLiteQueue):
    _TABLE_NAME = 'unique_queue'
    _SQL_CREATE = ('CREATE TABLE IF NOT EXISTS {table_name} ('
                   '{key_column} INTEGER PRIMARY KEY AUTOINCREMENT, '
                   'data BLOB, timestamp FLOAT, UNIQUE (data))')

    def put(self, item):
      obj = pickle.dumps(item)
      try:
        self._insert_into(obj, _time.time())
      except sqlite3.IntegrityError:
        #print("UNIQUE constraint failed")
        pass
      else:
        self.total += 1
        self.put_event.set()
```

**Comment by peter-wangxu** [comment]
Looks fine for me, but need to add some test to cover this.

To create PR, please follow below steps:
1. fork this project.
2. clone your forked project to local.
3. create a new branch, say `unique_queue`, then begin to make changes and commit.
4. `git push origin unique_queue`.
5. then your can create the PR based your branch by clicking the button `New pull request` on this [page](https://github.com/peter-wangxu/persist-queue/pulls).

**Comment by peter-wangxu** [comment]
@delica1 Do you meet any obstacle for the patch:)

**Comment by delica1** [comment]
Thanks for the instructions, Peter. Can't say I enjoyed the interface to do
this, but it worked out in the end (as far as I can tell).

**Comment by peter-wangxu** [comment]
Fixed in PR: https://github.com/peter-wangxu/persist-queue/pull/41
