### ISSUE TITLE
How secure is a `pdict` deletion? 

### ISSUE THREAD

**Issue by magistocrat** [peter-wangxu/persist-queue#44]
I'm curious about this line in [particular](https://github.com/peter-wangxu/persist-queue/blob/master/persistqueue/pdict.py#L65). To what degree does a dictionary entry deletion destroy the entry, is it overwritten in memory/disk?

**Comment by peter-wangxu** [comment]
It's as secure as the sqlite `delete` with transaction. It may or may not be overwritten. 

Let me know how `secure` you want it to be:)
Thanks
Peter

**Comment by magistocrat** [comment]
This [pragma](https://www.sqlite.org/pragma.html#pragma_secure_delete) tells SQLite to overwrite with zeroes when something is deleted, that should be sufficient for the usecase. I was just curious how to activate this functionality.

**Comment by peter-wangxu** [comment]
Closing it now, please open new issue if you have more.


Thanks
Peter
