### ISSUE TITLE
Use the highest protocol version for pickle

### ISSUE THREAD

**Issue by KennyRIM** [peter-wangxu/persist-queue#45]
By default pickle uses protocol version 0, which is ASCII and not so efficient (at least in terms of space).

**Comment by peter-wangxu** [comment]
What's the python version you are using, python2 and python3 supports different pickle versions.

I plan to use `Protocol version 2` to keep the best compatibility between python2 and python3

Thanks
Peter

**Comment by KennyRIM** [comment]
I use python 2.7 for my project (and it looks like my previous statement about default protocol is applicable only to 2.x, sorry for overlook).

However, I'd say that protocol compatibility is secondary for such queue, since it's not distributed. Only two processes on the same machine using different python versions could run into compatibility problem.

BR
Nick

**Comment by peter-wangxu** [comment]
@KennyRIM Do you have a chance to have a local test?

**Comment by KennyRIM** [comment]
Hi, 
- package's test ran ok in my env
- the project also runs fine
Thank you for the patch!

BR
Nick

**Comment by peter-wangxu** [comment]
Included in https://github.com/peter-wangxu/persist-queue/releases/tag/v0.3.6
