### ISSUE TITLE
Atomic renames on windows

### ISSUE THREAD

**Issue by Dobatymo** [peter-wangxu/persist-queue#48]
For python 3.3+ you can use https://docs.python.org/3/library/os.html#os.replace
For older python versions you can use https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx with `MOVEFILE_REPLACE_EXISTING` using `ctypes`.

**Comment by peter-wangxu** [comment]
Thanks for the suggestion, will investigate and try to implement it.

If you have already done or are willing to implement, let me know.

Thanks
Peter

**Comment by EverWinter23** [comment]
I want to implement it -- but I need more information on the issue.

**Comment by Dobatymo** [comment]
something like that https://github.com/peter-wangxu/persist-queue/pull/52

**Comment by peter-wangxu** [comment]
Hi @EverWinter23 
Current persist-queue is using non-atomic interfaces (os.rename/os.remove) https://github.com/peter-wangxu/persist-queue/blob/ff7bfa79238bbedb1f15bd108bc3f51ad443ae5d/persistqueue/queue.py#L226) on windows.

as @Dobatymo suggested, `ctypes` can be leveraged to achieve atomicity on Windows just like any POSIX platform.

BTW, As I could recall, Windows cannot remove an using file directly.

Thanks
Peter

**Comment by EverWinter23** [comment]
@peter-wangxu Thanks! :+1:

**Comment by peter-wangxu** [comment]
@EverWinter23 Do you need help or something blocks you?

**Comment by EverWinter23** [comment]
@peter-wangxu Want to add tests corresponding to the addition.

**Comment by peter-wangxu** [comment]
Which scenario you want to test, you may need to refer to the existing ones

**Comment by EverWinter23** [comment]
@peter-wangxu The rename one on windows since I cannot test it as my primary and only Os is Linux.

**Comment by peter-wangxu** [comment]
Did you notice the CI of your PR, it's running windows:)

**Comment by EverWinter23** [comment]
Yeah I did, but I don't know how to write tests. Help needed. Just point me in the right direction.

**Comment by peter-wangxu** [comment]
you need to add tests in the file:     https://github.com/peter-wangxu/persist-queue/blob/master/tests/test_queue.py
the tests look like below:
```python
    def test_open_close_single(self):
        """Write 1 item, close, reopen checking if same item is there"""

        q = Queue(self.path)
        q.put(b'var1')
        del q
        q = Queue(self.path)
        self.assertEqual(1, q.qsize())
        self.assertEqual(b'var1', q.get())
        q.task_done()
```

Since you change the logic of `task_done`, you need to compose a queue, putting/getting data and calling the `task_done` to make sure the code change is under test

**Comment by EverWinter23** [comment]
@peter-wangxu Will do. Thank You. :+1:

**Comment by EverWinter23** [comment]
@peter-wangxu I don't think we can add test cases corresponding to this commit as it does not involve
composing a Q. 

 class Queue(object):
     def __init__(self, path, maxsize=0, chunksize=100, tempdir=None):
         """Create a persistent queue object on a given path.
         tmpfd, tmpfn = self._gettempfile()
         os.write(tmpfd, pickle.dumps(self.info))
         os.close(tmpfd)
         atomic_rename(tmpfn, self._infopath())
         self._clear_tail_file()

**Comment by peter-wangxu** [comment]
@EverWinter23 Fine for me, since no blocking CI issue, I am ok to merge your PR.

**Comment by EverWinter23** [comment]
:+1:

**Comment by peter-wangxu** [comment]
Close it now, it had been resolved by https://github.com/peter-wangxu/persist-queue/pull/54
