### ISSUE TITLE
_qsize() discrepancy with multiple queue object sharing same dir

### ISSUE THREAD

**Issue by EmersonDing** [peter-wangxu/persist-queue#57]
Not sure if it's a bug or mis-usage. In the case that two queue object is defined with same path, e.g. 
```
q1 = Queue('path1')
q2 = Queue('path1')
q1.put(1)
q2.put(2)
```
Both q1.qsize() and q2.qsize() will be equal to 1, instead of 2. Because qsize() is calling _qsize(), which directly pull size from member variable `self.info['size']`, hence won't be aware the change from another object.

**Comment by peter-wangxu** [comment]
The two instances of queue are not aware of each other. You should share instance instead.

**Comment by peter-wangxu** [comment]
Closing it, as it is no an use case for persist-queue
