### ISSUE TITLE
Benchmarks are unclear to me

### ISSUE THREAD

**Issue by Ejxqzgds** [peter-wangxu/persist-queue#62]
There are no units given at the benchmarks. Is it a time value (e.g. `s`), i.e. higher values are worse, lower values are better? Or is it some kind of throughput (e.g. `Bytes/s`), which means higher values are better, lower are worse?

**Comment by peter-wangxu** [comment]
The benchmark measures the time spent in writing/reading <COUNT> items into disk, the less the better.
