### ISSUE TITLE
Implement AckQueue

### ISSUE THREAD

**Issue by relud** [peter-wangxu/persist-queue#68]
I want to try implementing `AckQueue` with raw file storage from `Queue` and ack support from`SQLiteAckQueue`.

Motivation: I need to reliably retry if I get transient exceptions when processing my queue, which is implemented most directly with ack support. I also need high performance, and the raw file storage in `Queue` performs faster than `SQLiteQueue` for me.

**Comment by peter-wangxu** [comment]
Hi @relud 
What's your device type, SSD or Hard Disk?

You can do a quick benchmark, below is the result on my Mac, which indicates sqlite3 is faster :)
```bash
(py27) ➜  benchmark git:(master) ✗ python run_benchmark.py 10000
<BENCHMARK_COUNT> = 10000
Benchmark File queue performance.

	Writing and reading <BENCHMARK_COUNT> items(1 task_done). => time used: 4.9223 seconds.
	Writing and reading <BENCHMARK_COUNT> items(many task_done). => time used: 9.7047 seconds.
	Writing <BENCHMARK_COUNT> items. => time used: 5.0401 seconds.
Benchmark Sqlite3 queue performance.
	Writing and reading <BENCHMARK_COUNT> items(1 task_done). => time used: 1.8976 seconds.
	Writing and reading <BENCHMARK_COUNT> items(many task_done). => time used: 3.1135 seconds.
	Writing <BENCHMARK_COUNT> items. => time used: 1.5582 seconds.
```

**Comment by relud** [comment]
ah, you're totally right! Thanks for pointing this out, I won't waste my time. I was using too small of tests 😅 .
