### ISSUE TITLE
Global `enable_callback_tracebacks` call prevents importing under pypy3

### ISSUE THREAD

**Issue by fake-name** [peter-wangxu/persist-queue#74]
I have a bunch of code that operates under both python3 and pypy3. 

Pypy has a complete `sqlite3` module, but they appear to not have implemented the non-DBAPI call `enable_callback_tracebacks()`. Currently, this is called unconditionally in multiple places on import of the `persistqueue` module.

```

durr@rwpscrape /m/S/S/ReadableWebProxy> pypy3
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
i>>>> import sqlite3
>>>> sqlite3.enable_callback_tracebacks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sqlite3' has no attribute 'enable_callback_tracebacks'

```

Setting aside the fact that this should really probably be called on the construction of a `SQLiteQueue` object, rather then globally on import (don't run code on import!), this also is apparently basically the one thing preventing the module from functioning under pypy.

I went through and manually edited the files to instead feature:

```
if not '__pypy__' in sys.builtin_module_names:
    sqlite3.enable_callback_tracebacks(True)
```

and it fixes the issue (you do also need to `import sys`).

**Comment by peter-wangxu** [comment]
@fake-name Got your concern, Can you please share your change and submit the PR?

My suggestion is to try .. catch the exception and ignore it , it's much pythonic:) in my opinion.

Thanks
Peter

**Comment by fake-name** [comment]
> My suggestion is to try .. catch the exception and ignore it , it's much pythonic:) in my opinion.

I considered that, but the thing is, you *do* want to know about issues if you're on CPython.

Anyways, I had performance issues with SQLite, so I've switched to just using redis.
