### ISSUE TITLE
ACK Queue: readme example for SQLiteAckQueue missing clear_acked_data()

### ISSUE THREAD

**Issue by employee-1234567** [peter-wangxu/persist-queue#77]
Unless I'm missing something, it seems the ACKQueue does not clean up after its self when you ACK the items. I discovered this function by looking over the unit tests. Is it expected that users call this function manually? It seems that ```clear_acked_data()``` should always be called after ```ackq.ack(item)``` if you don't want the sqlite DB to grow unbounded?

**Comment by peter-wangxu** [comment]
Looks like dup of #78

**Comment by employee-1234567** [comment]
I filed these as separate issues as I see this as a documentation issue. Basically, what this issue is asking is "do you expect users to explicitly call clear_acked_data()?" If so it should be added to the example in the readme and not left for someone to accidentally find it buried in the unit tests

**Comment by dcj** [comment]
Yes, I have this same question, should users explicitly call `clear_acked_data()`, and if so, when/how often?

**Comment by peter-wangxu** [comment]
please check it out in latest doc
