### ISSUE TITLE
SQLiteAckQueue get seems to treat falsy messages as not being present.

### ISSUE THREAD

**Issue by Schroedingers-Hat** [peter-wangxu/persist-queue#79]
Apologies if this is designed behavior, but I encountered an issue with falsy messages.

Python 3.7, sqlite 3.24.0
```
import persistqueue
q = persistqueue.SQLiteAckQueue('test')
q.put(0)
q.get()
```
Blocks instead of returning 0.

**Comment by peter-wangxu** [comment]
This is definitely a bug

**Comment by Schroedingers-Hat** [comment]
Anything I can do to assist reproduction further?

**Comment by peter-wangxu** [comment]
Fixed
