### ISSUE TITLE
File based queue: how to clean old files?

### ISSUE THREAD

**Issue by seatedscribe** [peter-wangxu/persist-queue#80]
I am using a file based queue and all is working as intended, except...

I would expect that after issuing `queue.task_done()` the file on disk would shrink, in order to reflect the actual size of the queue and, most important, to avoid files growing unbounded.

I missed to find a solution to this issue; someone can shed a light please?
Thanks!

**Comment by peter-wangxu** [comment]
Closing it now, it's inactive for a long time
