### ISSUE TITLE
SQLiteAckQueue file size growth

### ISSUE THREAD

**Issue by dcj** [peter-wangxu/persist-queue#84]
I am using a SQLiteAckQueue between threads.

Every 1 second, the producer thread reads a JSON file that is ~20K bytes, into a dict, which is `put` onto the queue, and then issues`task_done()`.  

The consumer thread blocks on `get`, then processes the queue-item, and when all goes well, calls `ack`, `task_done`, and finally `clear_acked_data`. 

After about 8 hours, the queue/database file sizes are:

```
-rw-r--r-- 1 2005 2005 32899072 Dec 10 15:35 data.db
-rw-r--r-- 1 2005 2005    32768 Dec 10 15:35 data.db-shm
-rw-r--r-- 1 2005 2005  4185952 Dec 10 15:35 data.db-wal
```
With the `.db` and `.db-wal` files continuing to growing over time.  Is this expected behavior, or am I doing something wrong?

Prior to discovering `clear_acked_data` via issues #78 and #77, these files sizes seemed to grow much faster, and eventually my application slowed to a crawl, AFAICT the persist-queue accesses to the database grew to unacceptable latencies.

**Comment by dcj** [comment]
90 minutes later, here are the file sizes:

**Comment by peter-wangxu** [comment]
@dcj any update on your tests?

Was the latencies mitigated by the clear_acked_data? i wonder if this is the sqlite issue with large files

**Comment by dcj** [comment]
Yes, I changed my code to:

- ack
- task_done
- clear_acked_data

After  I did this, the the file sizes do not get out of control, and the latency is fine (unmeasured, but my app doesn't slow to a crawl...)

FYI, in my application, every second I read a JSON file (size, 10-30 kbytes on disk), and convert it to a Python dict.  This dict is then put onto a persistent-queue.  Another thread reads the queue (as above)

I've been having a new problem where after a while there is a nasty disk error, and Linux remounts the device read-only.  This is on a Raspberry Pi, and the persistent-queue file is on a USB flash drive, formatted/mounted ext4, and persistent-queue is the ONLY thing on the system that uses/writes to that device/filesystem/directory.

I'm currently at a loss to fix this problem.  If I don't find a fix soon, I'll need to remove persist queue and use a memory based queue instead....

If you have any thoughts or ideas about how to prevent/solve this new problem, I'd love to hear them....

**Comment by peter-wangxu** [comment]
Good to know that. but this is the clear evidence that larger db files can slow down the sqlite performance dramatically:)

**Comment by peter-wangxu** [comment]
Closing it now, will update doc accordingly later

**Comment by peter-wangxu** [comment]
checkout latest doc.
