### ISSUE TITLE
Can't test if the queue is empty?

### ISSUE THREAD

**Issue by axfelix** [peter-wangxu/persist-queue#85]
Hi,

I like this module a lot, I'm just not getting something -- because this doesn't seem to implement `queue.empty()` unlike regular Python queue, I'm not sure how best to break out of a while loop, like:

```
    while True:
        if q_dir.empty():
            break
        else:
            path = q_dir.get()
            # do stuff
            q_dir.task_done()
```

Assuming I'm overlooking something simple. Thanks!

**Comment by peter-wangxu** [comment]
either, you can use `q.qsize()`
