### ISSUE TITLE
No exception raised when getting from empty queue

### ISSUE THREAD

**Issue by occoder** [peter-wangxu/persist-queue#91]
When I tried to get data from an empty queue, I was expecting to get an exception or None return.
But in fact, the program was hung up until ctrl+C was pushed.

**Comment by peter-wangxu** [comment]
The default behavior is to block until data reaches the queue again.
You can try:
```python
queue.get(block=false, timeout=5)
```

**Comment by occoder** [comment]
Yes, it works, though the document of this repository lacks such information.
Thanks for making it explicit.

**Comment by peter-wangxu** [comment]
Closing it as it's addressed by #93
