### ISSUE TITLE
How to do vacuum for persistqueue.SQLiteQueue

### ISSUE THREAD

**Issue by EnzoRondo** [peter-wangxu/persist-queue#95]
I want reduce size of file because it's inflated seriously even when queue is empty, and I see no ways to execute SQL 'vacuum' statement to reduce queue size on disk

how I can do that?

**Comment by peter-wangxu** [comment]
This lib may require an additional method to do this, you can also use guide in this PR: https://github.com/peter-wangxu/persist-queue/pull/82#issuecomment-444738084
