### ISSUE TITLE
Logger in SQLiteAckQueue produces UnicodeDecodeError as it tries to print item as a string (Python 2.7)

### ISSUE THREAD

**Issue by sgloutnikov** [peter-wangxu/persist-queue#96]
I stumbled upon a UnicodeDecodeError: 'ascii' codec can't decode byte... from the logger with certain values in SQLiteAckQueue + Python 2.7. After some investigation, it turns out that the problem lies with `log.warning("Can't find item %s from unack cache", item)` in combination with `from __future__ import unicode_literals` on Python 2.7. 

Possible solutions:
1) Remove `from __future__ import unicode_literals`
2) Don't log `item` at all, but acknowledge the warning.

I am personally more in favor of the second approach as I don't think it is safe to be logging items in this situation. Maybe they contain sensitive information, can be very large, etc. 

* Generally how to trigger the exception:

```
from __future__ import unicode_literals
import logging
import struct

foo = struct.pack("i", 255)
logging.warn("%s", foo)
```

* Example in SQLiteAckQueue:
```
q = SQLiteAckQueue('testdata', auto_resume=True)
inflight_map = dict()

# Generate some messages.
q.put('test')
q.put(struct.pack("i", 255))
q.put('test2')

# Publish message over network. Store 'in flight' messages
for id in range(3):
    foo = q.get()
    inflight_map[id] = foo

# Some time passes and no acknowledgement. Republish them.
time.sleep(1)
q.resume_unack_tasks()
for id in range(4, 7):
    foo = q.get()
    inflight_map[id] = foo

# Some more time passes, and server confirms original messages. Acknowledge them.
# _unack_cache now does not contain the items, and triggers the log with the printing of item as a string.
time.sleep(1)
for id in range(3):
    bar = inflight_map[id]
    q.ack(bar)
```

**Comment by peter-wangxu** [comment]
@sgloutnikov Agreed with you that should not log the item. I am going to propose a new PR later this week or do you mind send me the mentioned change?
